### ISSUE TITLE
Question : State of repo?

### ISSUE THREAD

**Issue by Nmans01** [timnghg/elysia-vite#1]
This seems pretty promising, so much so that Elysia features it on their homepage. Do you have plans to maintain it any further with new Elysia releases?

**Comment by masterT** [comment]
I have the same concern, it did not seems to be working in the latest version of Elysia

**Comment by timnghg** [comment]
It's maintaining.
Please upgrade to [0.2.0](https://www.npmjs.com/package/elysia-vite)
Please let me know if you have any problem.
