### ISSUE TITLE
Cannot find module 'elysia-vite'

### ISSUE THREAD

**Issue by sonicname** [timnghg/elysia-vite#2]
Cannot find module 'elysia-vite' or its corresponding type declarations. in version 0.1.0

**Comment by timnghg** [comment]
fixed, please update to 0.2.0 (0.1.0 is broken)

**Comment by simonedelmann** [comment]
I wanted to use elysia-vite in a new project, but I get the same typescript error all the time. (I am using Elysia 0.7.30 and elysia-vite 0.2.0)

```
import { elysiaVite } from 'elysia-vite'
```
Adding this line in a totally fresh Elysia project (`bun create elysia`) throws the following typescript error:
`Cannot find module 'elysia-vite' or its corresponding type declarations.`

@timnghg Do you maybe can have a look at this?
